import { useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import {
  BarChart3,
  Calendar,
  CheckCircle2,
  ClipboardList,
  Download,
  FileText,
  RefreshCw,
  ShieldAlert,
  TrendingUp,
} from 'lucide-react';
import Sidebar from '@/components/Sidebar';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { securityStore } from '@/security/securityStore';
import type { SecurityIncident, SecuritySeverity, SecurityStoreSnapshot } from '@/security/types';

type Period = 7 | 30 | 90;

const severityClass: Record<SecuritySeverity, string> = {
  critical: 'bg-red-500/20 text-red-300 border-red-500/30',
  high: 'bg-orange-500/20 text-orange-300 border-orange-500/30',
  medium: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
  low: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
  info: 'bg-gray-500/20 text-gray-300 border-gray-500/30',
};

function formatDate(value: string): string {
  return new Date(value).toLocaleString();
}

function downloadText(filename: string, content: string, type = 'text/plain'): void {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

function csvCell(value: string | number): string {
  return `"${String(value).replaceAll('"', '""')}"`;
}

function incidentReport(incident: SecurityIncident, snapshot: SecurityStoreSnapshot): string {
  const events = snapshot.events.filter((event) => incident.eventIds.includes(event.id));
  const detections = snapshot.detections.filter((detection) => incident.eventIds.includes(detection.eventId));
  const techniques = [...new Set(detections.flatMap((detection) => detection.mitreTechniques))];
  const indicators = [...new Set(events.flatMap((event) => [event.sourceIP, event.destinationIP, event.hostname, event.username].filter(Boolean)))];

  return [
    'J.A.R.V.I.S. INCIDENT INVESTIGATION REPORT',
    '============================================',
    `Incident ID: ${incident.id}`,
    `Title: ${incident.title}`,
    `Severity: ${incident.severity.toUpperCase()}`,
    `Status: ${incident.status.toUpperCase()}`,
    `Assignee: ${incident.assignee ?? 'Unassigned'}`,
    `Created: ${formatDate(incident.createdAt)}`,
    `Updated: ${formatDate(incident.updatedAt)}`,
    `Resolved: ${incident.resolvedAt ? formatDate(incident.resolvedAt) : 'Not resolved'}`,
    '',
    'SUMMARY',
    '-------',
    incident.description || 'No incident description recorded.',
    '',
    `Evidence events: ${events.length}`,
    `Detections: ${detections.length}`,
    `MITRE techniques: ${techniques.length ? techniques.join(', ') : 'None recorded'}`,
    `Indicators/assets: ${indicators.length ? indicators.join(', ') : 'None recorded'}`,
    '',
    'TIMELINE',
    '--------',
    ...events
      .sort((a, b) => a.timestamp.localeCompare(b.timestamp))
      .map((event) => `${formatDate(event.timestamp)} | ${event.category} | ${event.action ?? 'event'} | ${event.sourceIP ?? 'N/A'} | ${event.hostname ?? 'N/A'}`),
    '',
    'DETECTIONS',
    '----------',
    ...detections.map((detection) => `${detection.ruleName} | confidence ${Math.round(detection.confidence * 100)}% | ${detection.mitreTechniques.join(', ') || 'No MITRE mapping'}`),
    '',
    'Generated by J.A.R.V.I.S.',
    `Generated: ${new Date().toISOString()}`,
  ].join('\n');
}

export default function Reports() {
  const [snapshot, setSnapshot] = useState<SecurityStoreSnapshot>(securityStore.getSnapshot());
  const [period, setPeriod] = useState<Period>(30);
  const [selectedIncidentId, setSelectedIncidentId] = useState<string>('');

  useEffect(() => {
    securityStore.startBackendPolling();
    return () => securityStore.stopBackendPolling();
  }, []);

  useEffect(() => securityStore.subscribe(setSnapshot), []);

  const analytics = useMemo(() => {
    const cutoff = Date.now() - period * 24 * 60 * 60 * 1000;
    const events = snapshot.events.filter((event) => new Date(event.timestamp).getTime() >= cutoff);
    const detections = snapshot.detections.filter((detection) => new Date(detection.timestamp).getTime() >= cutoff);
    const incidents = snapshot.incidents.filter((incident) => new Date(incident.updatedAt).getTime() >= cutoff);
    const critical = incidents.filter((incident) => incident.severity === 'critical').length;
    const resolved = incidents.filter((incident) => incident.status === 'resolved').length;
    const open = incidents.filter((incident) => incident.status === 'open').length;
    const investigating = incidents.filter((incident) => incident.status === 'investigating').length;
    const severityCounts = (['critical', 'high', 'medium', 'low', 'info'] as SecuritySeverity[]).map((severity) => ({ severity, count: incidents.filter((incident) => incident.severity === severity).length }));
    const techniqueCounts = new Map<string, number>();
    for (const detection of detections) for (const technique of detection.mitreTechniques) techniqueCounts.set(technique, (techniqueCounts.get(technique) ?? 0) + 1);
    const topTechniques = [...techniqueCounts.entries()].map(([technique, count]) => ({ technique, count })).sort((a, b) => b.count - a.count).slice(0, 6);
    const averageConfidence = detections.length ? Math.round((detections.reduce((sum, detection) => sum + detection.confidence, 0) / detections.length) * 100) : 0;
    const resolutionHours = incidents.filter((incident) => incident.status === 'resolved' && incident.resolvedAt).map((incident) => (new Date(incident.resolvedAt!).getTime() - new Date(incident.createdAt).getTime()) / 3_600_000).filter((hours) => Number.isFinite(hours) && hours >= 0);
    const mttr = resolutionHours.length ? resolutionHours.reduce((sum, hours) => sum + hours, 0) / resolutionHours.length : null;
    return { events, detections, incidents, critical, resolved, open, investigating, severityCounts, topTechniques, averageConfidence, mttr };
  }, [snapshot, period]);

  const selectedIncident = analytics.incidents.find((incident) => incident.id === selectedIncidentId) ?? analytics.incidents[0];

  const exportCsv = () => {
    const rows = [['Incident ID', 'Title', 'Severity', 'Status', 'Assignee', 'Created', 'Updated', 'Evidence'], ...analytics.incidents.map((incident) => [incident.id, incident.title, incident.severity, incident.status, incident.assignee ?? 'Unassigned', incident.createdAt, incident.updatedAt, incident.eventIds.length])];
    downloadText(`jarvis-security-report-${period}d.csv`, rows.map((row) => row.map(csvCell).join(',')).join('\n'), 'text/csv;charset=utf-8');
  };

  const generateReport = () => {
    const lines = ['J.A.R.V.I.S. SECURITY REPORT', `Generated: ${new Date().toISOString()}`, `Reporting period: ${period} days`, '', `Incidents: ${analytics.incidents.length}`, `Critical incidents: ${analytics.critical}`, `Open: ${analytics.open}`, `Investigating: ${analytics.investigating}`, `Resolved: ${analytics.resolved}`, `Security events: ${analytics.events.length}`, `Detections: ${analytics.detections.length}`, `Average detection confidence: ${analytics.averageConfidence}%`, `Average MTTR: ${analytics.mttr === null ? 'N/A' : `${analytics.mttr.toFixed(1)}h`}`, '', 'TOP MITRE ATT&CK TECHNIQUES', ...analytics.topTechniques.map((item) => `${item.technique}: ${item.count} detections`)];
    downloadText(`jarvis-security-report-${period}d.txt`, lines.join('\n'));
  };

  const exportIncident = () => {
    if (!selectedIncident) return;
    downloadText(`jarvis-incident-${selectedIncident.id}.txt`, incidentReport(selectedIncident, snapshot));
  };

  const exportIncidentJson = () => {
    if (!selectedIncident) return;
    const evidence = snapshot.events.filter((event) => selectedIncident.eventIds.includes(event.id));
    const detections = snapshot.detections.filter((detection) => selectedIncident.eventIds.includes(detection.eventId));
    const payload = { incident: selectedIncident, evidence, detections, generatedAt: new Date().toISOString() };
    downloadText(`jarvis-incident-${selectedIncident.id}.json`, JSON.stringify(payload, null, 2), 'application/json');
  };

  return (
    <div className="flex h-screen bg-background text-foreground">
      <Sidebar />
      <main className="flex-1 overflow-auto">
        <div className="glass border-b sticky top-0 z-40">
          <div className="max-w-7xl mx-auto px-6 py-4">
            <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
              <div>
                <div className="flex items-center gap-3"><h1 className="text-3xl font-bold font-mono">REPORTS</h1><Badge className="bg-cyan-500/10 text-cyan-300 border-cyan-500/30 border">{snapshot.backendOnline ? 'LIVE DATA' : 'OFFLINE'}</Badge></div>
                <p className="text-sm text-muted-foreground">Security analytics calculated from persisted J.A.R.V.I.S. telemetry</p>
              </div>
              <div className="flex items-center gap-2 flex-wrap">
                <div className="flex rounded-md border border-border/40 overflow-hidden">{[7, 30, 90].map((value) => <Button key={value} size="sm" variant={period === value ? 'default' : 'ghost'} className="rounded-none font-mono" onClick={() => setPeriod(value as Period)}>{value}D</Button>)}</div>
                <Button variant="outline" size="sm" onClick={() => void securityStore.hydrateFromBackend()}><RefreshCw className="w-4 h-4" /></Button>
                <Button size="sm" onClick={generateReport} className="gap-2"><BarChart3 className="w-4 h-4" />Generate Report</Button>
              </div>
            </div>
          </div>
        </div>

        <div className="max-w-7xl mx-auto px-6 py-8">
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4 mb-8">
            <MetricCard label={`Incidents (${period}d)`} value={analytics.incidents.length} icon={<ShieldAlert className="w-4 h-4" />} />
            <MetricCard label="Detection Confidence" value={`${analytics.averageConfidence}%`} icon={<TrendingUp className="w-4 h-4" />} />
            <MetricCard label="Resolved" value={analytics.resolved} icon={<CheckCircle2 className="w-4 h-4" />} />
            <MetricCard label="Average MTTR" value={analytics.mttr === null ? 'N/A' : `${analytics.mttr.toFixed(1)}h`} icon={<Calendar className="w-4 h-4" />} />
          </div>

          <div className="grid grid-cols-1 xl:grid-cols-3 gap-6 mb-8">
            <Card className="glass glow-border p-6 xl:col-span-2"><div className="flex items-center justify-between mb-6"><div><h2 className="text-lg font-mono font-bold text-accent">SEVERITY DISTRIBUTION</h2><p className="text-xs text-muted-foreground mt-1">Persisted incidents in the selected period</p></div><span className="text-xs font-mono text-muted-foreground">{analytics.incidents.length} total</span></div><div className="space-y-4">{analytics.severityCounts.map(({ severity, count }) => { const percentage = analytics.incidents.length ? (count / analytics.incidents.length) * 100 : 0; const barClass = severityClass[severity].split(' ')[0].replace('/20', ''); return <div key={severity}><div className="flex justify-between items-center mb-1"><span className="text-xs font-mono uppercase">{severity}</span><span className="text-xs font-mono text-muted-foreground">{count}</span></div><div className="h-2 rounded-full bg-muted/30 overflow-hidden"><div className={`h-full rounded-full ${barClass}`} style={{ width: `${percentage}%` }} /></div></div>; })}</div></Card>
            <Card className="glass glow-border p-6"><h2 className="text-lg font-mono font-bold text-accent mb-1">INCIDENT STATE</h2><p className="text-xs text-muted-foreground mb-6">Current workflow distribution</p><div className="space-y-5"><StateRow label="Open" value={analytics.open} total={analytics.incidents.length} barClass="bg-red-400" /><StateRow label="Investigating" value={analytics.investigating} total={analytics.incidents.length} barClass="bg-yellow-400" /><StateRow label="Resolved" value={analytics.resolved} total={analytics.incidents.length} barClass="bg-green-400" /></div></Card>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
            <Card className="glass glow-border p-6"><div className="flex items-center justify-between mb-6"><div><h2 className="text-lg font-mono font-bold text-accent">MITRE ATT&CK COVERAGE</h2><p className="text-xs text-muted-foreground mt-1">Most frequently triggered techniques</p></div><FileText className="w-5 h-5 text-muted-foreground" /></div>{analytics.topTechniques.length ? <div className="space-y-3">{analytics.topTechniques.map((item, index) => <div key={item.technique} className="flex items-center gap-3"><span className="w-6 text-xs font-mono text-muted-foreground">0{index + 1}</span><span className="font-mono text-sm flex-1">{item.technique}</span><Badge variant="outline" className="font-mono">{item.count}</Badge></div>)}</div> : <EmptyState text="No MITRE detections in this period." />}</Card>
            <Card className="glass glow-border p-6"><div className="flex items-center justify-between mb-6"><div><h2 className="text-lg font-mono font-bold text-accent">REPORT EXPORTS</h2><p className="text-xs text-muted-foreground mt-1">Export the current reporting window</p></div><Download className="w-5 h-5 text-muted-foreground" /></div><div className="space-y-3"><Button variant="outline" className="w-full justify-between" onClick={generateReport}><span className="flex items-center gap-2"><FileText className="w-4 h-4" />Executive text report</span><span className="text-xs text-muted-foreground">TXT</span></Button><Button variant="outline" className="w-full justify-between" onClick={exportCsv}><span className="flex items-center gap-2"><Download className="w-4 h-4" />Incident dataset</span><span className="text-xs text-muted-foreground">CSV</span></Button></div><div className="mt-6 pt-4 border-t border-border/20 text-xs text-muted-foreground font-mono">Generated from {analytics.events.length} events, {analytics.detections.length} detections and {analytics.incidents.length} incidents.</div></Card>
          </div>

          <Card className="glass glow-border p-6 mb-8">
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 mb-5">
              <div><h2 className="text-lg font-mono font-bold text-accent">INCIDENT INVESTIGATION EXPORT</h2><p className="text-xs text-muted-foreground mt-1">Package one persisted incident with its evidence and detections.</p></div>
              <div className="flex items-center gap-2 flex-wrap">
                <select value={selectedIncident?.id ?? ''} onChange={(event) => setSelectedIncidentId(event.target.value)} className="h-9 min-w-[260px] rounded-md border border-border/40 bg-background px-3 text-sm font-mono">
                  {analytics.incidents.length ? analytics.incidents.map((incident) => <option key={incident.id} value={incident.id}>{incident.title} · {incident.id}</option>) : <option value="">No incidents</option>}
                </select>
                <Button variant="outline" disabled={!selectedIncident} onClick={exportIncident}><ClipboardList className="w-4 h-4 mr-2" />TXT</Button>
                <Button variant="outline" disabled={!selectedIncident} onClick={exportIncidentJson}><Download className="w-4 h-4 mr-2" />JSON</Button>
              </div>
            </div>
            {selectedIncident ? <div className="grid grid-cols-1 md:grid-cols-4 gap-3"><MiniStat label="Severity" value={selectedIncident.severity.toUpperCase()} /><MiniStat label="Status" value={selectedIncident.status.toUpperCase()} /><MiniStat label="Evidence" value={selectedIncident.eventIds.length} /><MiniStat label="Assignee" value={selectedIncident.assignee ?? 'Unassigned'} /></div> : <EmptyState text="No incidents available for investigation export." />}
          </Card>

          <Card className="glass glow-border p-6"><div className="flex items-center justify-between mb-5"><div><h2 className="text-lg font-mono font-bold text-accent">RECENT INCIDENT ACTIVITY</h2><p className="text-xs text-muted-foreground mt-1">Latest persisted incidents available for investigation</p></div><span className="text-xs font-mono text-muted-foreground">{analytics.incidents.length} in window</span></div>{analytics.incidents.length ? <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b border-border/20 text-xs text-muted-foreground font-mono"><th className="py-3 pr-4">INCIDENT</th><th className="py-3 pr-4">SEVERITY</th><th className="py-3 pr-4">STATUS</th><th className="py-3 pr-4">EVIDENCE</th><th className="py-3">UPDATED</th></tr></thead><tbody>{[...analytics.incidents].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, 10).map((incident) => <tr key={incident.id} className="border-b border-border/10 last:border-0"><td className="py-3 pr-4"><p className="font-mono text-sm font-bold">{incident.title}</p><p className="font-mono text-[10px] text-muted-foreground">{incident.id}</p></td><td className="py-3 pr-4"><Badge className={`${severityClass[incident.severity]} border`}>{incident.severity.toUpperCase()}</Badge></td><td className="py-3 pr-4"><span className="text-xs font-mono uppercase">{incident.status}</span></td><td className="py-3 pr-4 text-sm font-mono">{incident.eventIds.length}</td><td className="py-3 text-xs font-mono text-muted-foreground">{formatDate(incident.updatedAt)}</td></tr>)}</tbody></table></div> : <EmptyState text="No persisted incidents in the selected period. Run a safe Attack Lab scenario to populate analytics." />}</Card>
        </div>
      </main>
    </div>
  );
}

function MetricCard({ label, value, icon }: { label: string; value: string | number; icon: ReactNode }) { return <Card className="glass glow-border p-5"><div className="flex items-center justify-between mb-3"><p className="text-xs text-muted-foreground font-mono uppercase">{label}</p><span className="text-cyan-400">{icon}</span></div><p className="text-3xl font-mono font-bold text-cyan-400">{value}</p></Card>; }
function MiniStat({ label, value }: { label: string; value: string | number }) { return <div className="rounded-md border border-border/30 bg-muted/10 p-3"><p className="text-[10px] uppercase font-mono text-muted-foreground">{label}</p><p className="text-sm font-mono font-semibold mt-1 truncate">{value}</p></div>; }
function StateRow({ label, value, total, barClass }: { label: string; value: number; total: number; barClass: string }) { const percentage = total ? Math.round((value / total) * 100) : 0; return <div><div className="flex items-center justify-between mb-1"><span className="text-sm font-mono">{label}</span><span className="text-xs font-mono text-muted-foreground">{value} · {percentage}%</span></div><div className="h-2 rounded-full bg-muted/30 overflow-hidden"><div className={`h-full rounded-full ${barClass}`} style={{ width: `${percentage}%` }} /></div></div>; }
function EmptyState({ text }: { text: string }) { return <div className="py-10 text-center text-sm text-muted-foreground font-mono">{text}</div>; }
