import { useMemo } from 'react';
import { ShieldAlert, Clock3, CheckCircle2, ArrowRight, Activity } from 'lucide-react';
import Sidebar from '@/components/Sidebar';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { securityStore } from '@/security/securityStore';
import { useSecurityStore } from '@/security/useSecurityStore';

export default function ResponseCenter() {
  const snapshot = useSecurityStore(securityStore);
  const priority = useMemo(() => [...snapshot.incidentThreads].sort((a,b) => ({critical:4,high:3,medium:2,low:1,info:0}[b.severity] ?? 0)-({critical:4,high:3,medium:2,low:1,info:0}[a.severity] ?? 0)), [snapshot.incidentThreads]);
  const open = priority.filter(i => i.status !== 'resolved');
  return <div className="flex h-screen bg-background text-foreground"><Sidebar/><main className="flex-1 overflow-auto"><header className="glass border-b sticky top-0 z-40"><div className="max-w-7xl mx-auto px-6 py-5"><div className="flex items-center gap-3"><ShieldAlert className="w-6 h-6 text-accent"/><div><h1 className="text-3xl font-bold font-mono">RESPONSE CENTER</h1><p className="text-sm text-muted-foreground">Prioritize, investigate and coordinate active security response</p></div></div></div></header><div className="max-w-7xl mx-auto p-6 space-y-6"><div className="grid grid-cols-1 md:grid-cols-4 gap-4"><Metric label="ACTIVE INCIDENTS" value={open.length} icon={<ShieldAlert/>}/><Metric label="CRITICAL" value={open.filter(i=>i.severity==='critical').length} icon={<Activity/>}/><Metric label="INVESTIGATING" value={open.filter(i=>i.status==='investigating').length} icon={<Clock3/>}/><Metric label="RESOLVED" value={priority.filter(i=>i.status==='resolved').length} icon={<CheckCircle2/>}/></div><Card className="glass glow-border p-6"><div className="flex items-center justify-between mb-5"><div><h2 className="font-mono font-bold text-accent">RESPONSE QUEUE</h2><p className="text-xs text-muted-foreground mt-1">Incidents ordered by severity and investigation state</p></div><span className="text-xs font-mono text-muted-foreground">{open.length} ACTIVE</span></div><div className="space-y-3">{open.length===0?<p className="py-10 text-center text-muted-foreground">No active incidents.</p>:open.map(incident=><div key={incident.id} className="p-4 rounded-lg border border-border/30 bg-card/30 flex items-center gap-4"><div className={`w-2 h-12 rounded-full ${incident.severity==='critical'?'bg-destructive':incident.severity==='high'?'bg-orange-400':'bg-accent'}`}/><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><span className="font-mono font-bold truncate">{incident.title}</span><span className="text-[10px] uppercase px-2 py-1 rounded border border-border/30">{incident.severity}</span></div><p className="text-xs text-muted-foreground mt-1">{incident.eventIds.length} events · {incident.detectionIds.length} detections · {incident.status}</p></div><Button variant="outline" size="sm" onClick={()=>window.location.assign(`/incidents?incident=${encodeURIComponent(incident.id)}`)}>Investigate <ArrowRight className="w-4 h-4 ml-1"/></Button></div>)}</div></Card></div></main></div>;
}
function Metric({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <Card className="glass p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-mono text-muted-foreground">{label}</p><p className="text-2xl font-mono font-bold mt-1">{value}</p></div><span className="text-accent">{icon}</span></div></Card>}
