import { Router } from 'express';
import { z } from 'zod';
import { nanoid } from 'nanoid';
import { evaluateEvent } from './detectionEngine';
import { addDetection, addEvent, addIncident, addIncidentActivity, addIncidentNote, addIoc, deleteIoc, getDevices, getDetections, getEvents, getIncidentById, getIncidentDetail, getIncidents, getIocContext, getIocs, getSnapshot } from './store';
import { requireDb } from './db';
import type { SecurityEvent, SecurityIncident, SecuritySeverity } from './types';
const router=Router();
const securityEventSchema=z.object({id:z.string().min(1),timestamp:z.string().datetime(),type:z.enum(['authentication','network','process','file','malware','privilege','exfiltration','dns','web','system','detection']),source:z.enum(['simulation','suricata','zeek','splunk','endpoint','firewall','identity','manual']),sourceSystem:z.string().optional(),title:z.string().min(1).max(300),description:z.string().min(1).max(5000),severity:z.enum(['critical','high','medium','low','info']),sourceIP:z.string().optional(),destinationIP:z.string().optional(),sourcePort:z.number().int().min(0).max(65535).optional(),destinationPort:z.number().int().min(0).max(65535).optional(),protocol:z.string().optional(),hostname:z.string().optional(),username:z.string().optional(),processName:z.string().optional(),filePath:z.string().optional(),mitreTechniques:z.array(z.string()).optional(),scenarioId:z.string().optional(),metadata:z.record(z.string(),z.unknown()).optional()});
const severityRank:Record<SecuritySeverity,number>={info:0,low:1,medium:2,high:3,critical:4};
function highestSeverity(values:SecuritySeverity[]):SecuritySeverity{return values.reduce<SecuritySeverity>((h,v)=>severityRank[v]>severityRank[h]?v:h,'info');}
function correlationKeys(event:SecurityEvent):string[]{return [event.sourceIP?`ip:${event.sourceIP}`:null,event.hostname?`host:${event.hostname}`:null,event.username?`user:${event.username}`:null,event.scenarioId?`scenario:${event.scenarioId}`:null].filter((v):v is string=>Boolean(v));}
function shareCorrelationKey(a:SecurityEvent,b:SecurityEvent):boolean{const keys=new Set(correlationKeys(a));return correlationKeys(b).some(k=>keys.has(k));}
function actorFromRequest(req:{header(name:string):string|undefined}):string{return req.header('X-JARVIS-Actor')?.trim()||'SOC Analyst';}
async function createIncidentFromDetection(event:SecurityEvent,detection:Awaited<ReturnType<typeof evaluateEvent>>[number]){const recentEvents=(await getEvents(1000)).filter(c=>Math.abs(new Date(event.timestamp).getTime()-new Date(c.timestamp).getTime())<=10*60*1000&&shareCorrelationKey(event,c));if(recentEvents.length<2)return null;const ids=recentEvents.map(i=>i.id), recentDetections=(await getDetections(500)).filter(i=>ids.includes(i.eventId));if(!recentDetections.length)return null;const existing=(await getIncidents(500)).find(i=>i.status!=='resolved'&&i.eventIds.some(id=>ids.includes(id)));const now=new Date().toISOString();const techniques=Array.from(new Set(recentDetections.flatMap(i=>i.mitreTechniques)));const incident:SecurityIncident={id:existing?.id??`inc-${nanoid(10)}`,title:existing?.title??`${detection.ruleName} activity detected${techniques.length?` [${techniques.slice(0,3).join(' → ')}]`:''}`,severity:highestSeverity([detection.severity,...recentDetections.map(i=>i.severity)]),status:existing?.status??'investigating',eventIds:Array.from(new Set([...(existing?.eventIds??[]),...ids])),detectionIds:Array.from(new Set([...(existing?.detectionIds??[]),...recentDetections.map(i=>i.id)])),assignee:existing?.assignee,resolvedAt:existing?.resolvedAt,createdAt:existing?.createdAt??now,updatedAt:now};const persisted=await addIncident(incident);if(!existing)await addIncidentActivity(persisted.id,'incident_created','J.A.R.V.I.S.',{severity:persisted.severity,detectionId:detection.id});return persisted;}
router.get('/health',async(_req,res)=>res.json({success:true,data:{service:'jarvis-security-api',status:'online'}}));
router.get('/snapshot',async(_req,res,next)=>{try{res.json({success:true,data:await getSnapshot()});}catch(e){next(e);}});
router.get('/events',async(req,res,next)=>{try{const n=Number(req.query.limit??100);res.json({success:true,data:await getEvents(Number.isFinite(n)?Math.max(1,Math.min(n,1000)):100)});}catch(e){next(e);}});
router.post('/events',async(req,res,next)=>{try{const parsed=securityEventSchema.safeParse(req.body?.event??req.body);if(!parsed.success)return res.status(400).json({success:false,error:'Invalid security event payload',details:parsed.error.flatten()});const event=parsed.data as SecurityEvent;const history=await getEvents(1000);await addEvent(event);const detections=evaluateEvent(event,history);for(const d of detections)await addDetection(d);const incidents:SecurityIncident[]=[];for(const d of detections){const incident=await createIncidentFromDetection(event,d);if(incident)incidents.push(incident);}return res.status(201).json({success:true,data:{event,detections,incidents,ingestionId:nanoid()}});}catch(e){next(e);}});
router.get('/detections',async(req,res,next)=>{try{const n=Number(req.query.limit??100);res.json({success:true,data:await getDetections(Number.isFinite(n)?Math.max(1,Math.min(n,500)):100)});}catch(e){next(e);}});
router.get('/incidents',async(_req,res,next)=>{try{res.json({success:true,data:await getIncidents()});}catch(e){next(e);}});
router.get('/incidents/:id',async(req,res,next)=>{try{const detail=await getIncidentDetail(req.params.id);if(!detail)return res.status(404).json({success:false,error:'Incident not found'});res.json({success:true,data:detail});}catch(e){next(e);}});
router.patch('/incidents/:id/status',async(req,res,next)=>{try{const parsed=z.object({status:z.enum(['open','investigating','resolved'])}).safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:'Invalid incident status'});const incident=await getIncidentById(req.params.id);if(!incident)return res.status(404).json({success:false,error:'Incident not found'});if(incident.status===parsed.data.status)return res.json({success:true,data:incident});const actor=actorFromRequest(req),db=requireDb(),resolvedAt=parsed.data.status==='resolved'?new Date().toISOString():null;await db.query('UPDATE security_incidents SET status=$1,resolved_at=$2,updated_at=NOW() WHERE id=$3',[parsed.data.status,resolvedAt,req.params.id]);const updated=await getIncidentById(req.params.id);if(!updated)return res.status(404).json({success:false,error:'Incident not found after update'});await addIncidentActivity(updated.id,`status_changed:${parsed.data.status}`,actor,{previousStatus:incident.status,status:updated.status});res.json({success:true,data:updated});}catch(e){next(e);}});
router.patch('/incidents/:id/assignee',async(req,res,next)=>{try{const parsed=z.object({assignee:z.string().trim().min(1).max(200)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:'Assignee is required'});const incident=await getIncidentById(req.params.id);if(!incident)return res.status(404).json({success:false,error:'Incident not found'});const actor=actorFromRequest(req),db=requireDb();await db.query('UPDATE security_incidents SET assignee=$1,updated_at=NOW() WHERE id=$2',[parsed.data.assignee,req.params.id]);const updated=await getIncidentById(req.params.id);if(!updated)return res.status(404).json({success:false,error:'Incident not found after update'});await addIncidentActivity(updated.id,'assignee_changed',actor,{previousAssignee:incident.assignee??null,assignee:updated.assignee});res.json({success:true,data:updated});}catch(e){next(e);}});
router.post('/incidents/:id/notes',async(req,res,next)=>{try{const parsed=z.object({body:z.string().trim().min(1).max(10000)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:'Note body is required'});const incident=await getIncidentById(req.params.id);if(!incident)return res.status(404).json({success:false,error:'Incident not found'});const actor=actorFromRequest(req),note=await addIncidentNote(incident.id,actor,parsed.data.body);await addIncidentActivity(incident.id,'note_added',actor,{noteId:note.id});res.status(201).json({success:true,data:note});}catch(e){next(e);}});
router.get('/incidents/:id/notes',async(req,res,next)=>{try{const d=await getIncidentDetail(req.params.id);if(!d)return res.status(404).json({success:false,error:'Incident not found'});res.json({success:true,data:d.notes});}catch(e){next(e);}});
router.get('/incidents/:id/activity',async(req,res,next)=>{try{const d=await getIncidentDetail(req.params.id);if(!d)return res.status(404).json({success:false,error:'Incident not found'});res.json({success:true,data:d.activity});}catch(e){next(e);}});
const iocSchema=z.object({type:z.enum(['ip','domain','hash','url']),value:z.string().trim().min(2).max(2048),severity:z.enum(['critical','high','medium','low','info']),tags:z.array(z.string().trim().min(1).max(50)).max(20).optional(),confidence:z.number().int().min(0).max(100).optional()});
router.get('/iocs',async(_req,res,next)=>{try{res.json({success:true,data:await getIocs()});}catch(e){next(e);}});
router.get('/iocs/:id/context',async(req,res,next)=>{try{const context=await getIocContext(req.params.id);if(!context)return res.status(404).json({success:false,error:'IOC not found'});res.json({success:true,data:context});}catch(e){next(e);}});
router.post('/iocs',async(req,res,next)=>{try{const parsed=iocSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:'Invalid IOC payload',details:parsed.error.flatten()});const actor=actorFromRequest(req);const value=parsed.data.value.toLowerCase();const ioc=await addIoc({id:`ioc-${nanoid(12)}`,...parsed.data,value,source:actor});res.status(201).json({success:true,data:ioc});}catch(e){next(e);}});
router.delete('/iocs/:id',async(req,res,next)=>{try{const ioc=await deleteIoc(req.params.id);if(!ioc)return res.status(404).json({success:false,error:'IOC not found'});res.json({success:true,data:ioc});}catch(e){next(e);}});
router.get('/devices',async(_req,res,next)=>{try{res.json({success:true,data:await getDevices()});}catch(e){next(e);}});
export default router;
