import { Router } from 'express';
import { nanoid } from 'nanoid';
import { z } from 'zod';
import { createSession, destroySession, getAuthUser, hashPassword, setSessionCookie, clearSessionCookie, verifyPassword } from './auth';

const router = Router();
const credentials = z.object({ email: z.string().trim().email().max(320), password: z.string().min(8).max(200), name: z.string().trim().min(2).max(100).optional() });
function cookie(req: { headers: { cookie?: string } }) { return req.headers.cookie?.split(';').map(v => v.trim()).find(v => v.startsWith('jarvis_session='))?.slice('jarvis_session='.length); }
router.get('/me', async (req, res, next) => { try { const user = await getAuthUser(cookie(req)); res.json({ success: true, data: user }); } catch (e) { next(e); } });
router.post('/signup', async (req, res, next) => { try { const parsed = credentials.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: 'Use a valid email and a password of at least 8 characters.' }); const { email, password, name } = parsed.data; const db = (await import('./security/db')).requireDb(); const exists = await db.query('SELECT id FROM auth_users WHERE email=$1', [email.toLowerCase()]); if (exists.rowCount) return res.status(409).json({ success: false, error: 'An account with this email already exists.' }); const id = `usr-${nanoid(12)}`; await db.query('INSERT INTO auth_users (id,email,name,password_hash,role) VALUES ($1,$2,$3,$4,$5)', [id, email.toLowerCase(), name || email.split('@')[0], await hashPassword(password), 'analyst']); const token = await createSession(id); setSessionCookie(res, token); const user = await getAuthUser(token); res.status(201).json({ success: true, data: user }); } catch (e) { next(e); } });
router.post('/signin', async (req, res, next) => { try { const parsed = credentials.pick({ email: true, password: true }).safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: 'Invalid credentials.' }); const db = (await import('./security/db')).requireDb(); const result = await db.query('SELECT id,password_hash FROM auth_users WHERE email=$1', [parsed.data.email.toLowerCase()]); if (!result.rows[0] || !(await verifyPassword(parsed.data.password, result.rows[0].password_hash))) return res.status(401).json({ success: false, error: 'Invalid email or password.' }); const token = await createSession(result.rows[0].id); setSessionCookie(res, token); res.json({ success: true, data: await getAuthUser(token) }); } catch (e) { next(e); } });
router.post('/logout', async (req, res, next) => { try { await destroySession(cookie(req)); clearSessionCookie(res); res.json({ success: true, data: { loggedOut: true } }); } catch (e) { next(e); } });
export default router;
