import { createHash, randomBytes, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto'; import { promisify } from 'node:util'; import type { Request, Response, NextFunction } from 'express'; import { requireDb } from './security/db';
const scrypt=promisify(scryptCallback); const SESSION_COOKIE='jarvis_session'; const SESSION_TTL_MS=1000*60*60*24*7;
export type AuthRole='admin'|'analyst'|'viewer'; export interface AuthUser{id:string;email:string;name:string;role:AuthRole;createdAt?:string;}
function hashSession(token:string){return createHash('sha256').update(token).digest('hex');} function readCookie(req:Request){return req.headers.cookie?.split(';').map(v=>v.trim()).find(v=>v.startsWith(`${SESSION_COOKIE}=`))?.slice(SESSION_COOKIE.length+1);}
export async function hashPassword(password:string){const salt=randomBytes(16).toString('hex');const derived=(await scrypt(password,salt,64)) as Buffer;return `scrypt:${salt}:${derived.toString('hex')}`;} export async function verifyPassword(password:string,stored:string){const [,salt,hash]=stored.split(':');if(!salt||!hash)return false;const derived=(await scrypt(password,salt,64)) as Buffer;const expected=Buffer.from(hash,'hex');return expected.length===derived.length&&timingSafeEqual(expected,derived);}
export async function createSession(userId:string){const token=randomBytes(32).toString('base64url');await requireDb().query("INSERT INTO auth_sessions (token_hash,user_id,expires_at) VALUES ($1,$2,NOW()+INTERVAL '7 days')",[hashSession(token),userId]);return token;} export async function destroySession(token:string|undefined){if(token)await requireDb().query('DELETE FROM auth_sessions WHERE token_hash=$1',[hashSession(token)]);} export async function getAuthUser(token:string|undefined):Promise<AuthUser|null>{if(!token)return null;const result=await requireDb().query('SELECT u.id,u.email,u.name,u.role,u.created_at FROM auth_sessions s JOIN auth_users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>NOW()',[hashSession(token)]);return result.rows[0]?{id:result.rows[0].id,email:result.rows[0].email,name:result.rows[0].name,role:result.rows[0].role as AuthRole,createdAt:result.rows[0].created_at}:null;}
export function setSessionCookie(res:Response,token:string){res.setHeader('Set-Cookie',`${SESSION_COOKIE}=${token}; Max-Age=${SESSION_TTL_MS/1000}; Path=/; HttpOnly; SameSite=Lax${process.env.NODE_ENV==='production'?'; Secure':''}`);} export function clearSessionCookie(res:Response){res.setHeader('Set-Cookie',`${SESSION_COOKIE}=; Max-Age=0; Path=/; HttpOnly; SameSite=Lax${process.env.NODE_ENV==='production'?'; Secure':''}`);}
export async function requireAuth(req:Request,res:Response,next:NextFunction){try{const user=await getAuthUser(readCookie(req));if(!user)return res.status(401).json({success:false,error:'Authentication required'});res.locals.user=user;next();}catch(error){next(error);}}
export function requireRole(...roles:AuthRole[]){return (req:Request,res:Response,next:NextFunction)=>{const user=res.locals.user as AuthUser|undefined;if(!user)return res.status(401).json({success:false,error:'Authentication required'});if(!roles.includes(user.role))return res.status(403).json({success:false,error:'Insufficient permissions'});next();};} export async function currentUser(req:Request){return getAuthUser(readCookie(req));}
