import { Router } from 'express'; import { nanoid } from 'nanoid'; import { z } from 'zod'; import { createSession, destroySession, getAuthUser, hashPassword, setSessionCookie, clearSessionCookie, verifyPassword, requireAuth, requireRole, type AuthRole } from './auth';
const router=Router(); const credentials=z.object({email:z.string().trim().email().max(320),password:z.string().min(8).max(200),name:z.string().trim().min(2).max(100).optional()}); const roleSchema=z.enum(['admin','analyst','viewer']); function cookie(req:{headers:{cookie?:string}}){return req.headers.cookie?.split(';').map(v=>v.trim()).find(v=>v.startsWith('jarvis_session='))?.slice('jarvis_session='.length);}
router.get('/me',async(req,res,next)=>{try{res.json({success:true,data:await getAuthUser(cookie(req))});}catch(e){next(e);}});
router.post('/signup',async(req,res,next)=>{try{const parsed=credentials.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:'Use a valid email and a password of at least 8 characters.'});const {email,password,name}=parsed.data;const db=(await import('./security/db')).requireDb();const exists=await db.query('SELECT id FROM auth_users WHERE email=$1',[email.toLowerCase()]);if(exists.rowCount)return res.status(409).json({success:false,error:'An account with this email already exists.'});const id=`usr-${nanoid(12)}`;await db.query('INSERT INTO auth_users (id,email,name,password_hash,role) VALUES ($1,$2,$3,$4,$5)',[id,email.toLowerCase(),name||email.split('@')[0],await hashPassword(password),'analyst']);const token=await createSession(id);setSessionCookie(res,token);res.status(201).json({success:true,data:await getAuthUser(token)});}catch(e){next(e);}});
router.post('/signin',async(req,res,next)=>{try{const parsed=credentials.pick({email:true,password:true}).safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:'Invalid credentials.'});const db=(await import('./security/db')).requireDb();const result=await db.query('SELECT id,password_hash FROM auth_users WHERE email=$1',[parsed.data.email.toLowerCase()]);if(!result.rows[0]||!(await verifyPassword(parsed.data.password,result.rows[0].password_hash)))return res.status(401).json({success:false,error:'Invalid email or password.'});const token=await createSession(result.rows[0].id);setSessionCookie(res,token);res.json({success:true,data:await getAuthUser(token)});}catch(e){next(e);}});
router.post('/logout',async(req,res,next)=>{try{await destroySession(cookie(req));clearSessionCookie(res);res.json({success:true,data:{loggedOut:true}});}catch(e){next(e);}});
router.use(requireAuth,requireRole('admin'));
router.get('/users',async(_req,res,next)=>{try{const rows=await (await import('./security/db')).requireDb().query("SELECT id,email,name,role,created_at FROM auth_users ORDER BY created_at DESC");res.json({success:true,data:rows.rows.map(r=>({id:r.id,email:r.email,name:r.name,role:r.role,createdAt:r.created_at}))});}catch(e){next(e);}});
router.patch('/users/:id/role',async(req,res,next)=>{try{const parsed=z.object({role:roleSchema}).safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:'Invalid role.'});const id=req.params.id;const actor=res.locals.user as {id:string};if(actor.id===id&&parsed.data.role!=='admin')return res.status(400).json({success:false,error:'You cannot remove your own admin role.'});const db=(await import('./security/db')).requireDb();const result=await db.query('UPDATE auth_users SET role=$1 WHERE id=$2 RETURNING id,email,name,role,created_at',[parsed.data.role,id]);if(!result.rowCount)return res.status(404).json({success:false,error:'User not found.'});res.json({success:true,data:{...result.rows[0],createdAt:result.rows[0].created_at}});}catch(e){next(e);}});
router.delete('/users/:id',async(req,res,next)=>{try{const actor=res.locals.user as {id:string};if(actor.id===req.params.id)return res.status(400).json({success:false,error:'You cannot delete your own account.'});const db=(await import('./security/db')).requireDb();const result=await db.query('DELETE FROM auth_users WHERE id=$1 RETURNING id',[req.params.id]);if(!result.rowCount)return res.status(404).json({success:false,error:'User not found.'});res.json({success:true,data:{id:req.params.id,deleted:true}});}catch(e){next(e);}});
router.get('/users/:id/sessions',async(req,res,next)=>{try{const db=(await import('./security/db')).requireDb();const result=await db.query('SELECT created_at,expires_at FROM auth_sessions WHERE user_id=$1 ORDER BY created_at DESC',[req.params.id]);res.json({success:true,data:result.rows});}catch(e){next(e);}});
export default router;
